title: Zach Goebel
email: hello@zachgoebel.com
description: >
  Operator. Builder. Writer. Musician.
  A public notebook of projects, experiments, and ideas.

baseurl: "/zachgoebel.com"
url: "https://zach-goebel.github.io"

markdown: kramdown
permalink: /writing/:title/

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
